eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
     defaultZone: http://localhost:8080/Eureka-Server-0.0.1-SNAPSHOT/
  instance:
    hostname: localhost
    
microservice:
 order-service:
  endpoints:
   endpoint:
    uri: http://ORDER-SERVICE/api/order/book
 payment-service:
  endpoints:
   endpoint:
    uri: http://PAYMENT-SERVICE/api/payment/pay    
