eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
     defaultZone: http://eurekaserver-env.eba-trzeikiq.us-east-2.elasticbeanstalk.com/
  instance:
    hostname: localhost
    
microservice:
 order-service:
  endpoints:
   endpoint:
    uri: http://ORDER-SERVICE/api/order/book
 payment-service:
  endpoints:
   endpoint:
    uri: http://PAYMENT-SERVICE/api/payment/pay    
