eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: EUREKA-SERVER
    
microservice:
 order-service:
  endpoints:
   endpoint:
    uri: http://ORDER-SERVICE/api/order/book
 payment-service:
  endpoints:
   endpoint:
    uri: http://PAYMENT-SERVICE/api/payment/pay    
