eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: http://eurekaserver-env.eba-trzeikiq.us-east-2.elasticbeanstalk.com/
    
microservice:
 order-service:
  endpoints:
   endpoint:
    uri: http://ORDER-SERVICE/api/order/book
 order-service:
  endpoints:
   endpoint:
    uri: http://PAYMENT-SERVICE/api/payment/pay    
